/*DATE BLOCKS*/


/* January */
((SUM(CASE WHEN {trandate} BETWEEN TO_DATE(TO_CHAR(SYSDATE, 'YYYY') || '-01-01', 'YYYY-MM-DD')AND TO_DATE(TO_CHAR(SYSDATE, 'YYYY') || '-01-31', 'YYYY-MM-DD') THEN {amount} ELSE 0 END) - 
SUM( CASE WHEN {trandate} BETWEEN ADD_MONTHS(TO_DATE(TO_CHAR(SYSDATE, 'YYYY') || '-01-01', 'YYYY-MM-DD'), -12) AND ADD_MONTHS(TO_DATE(TO_CHAR(SYSDATE, 'YYYY') || '-01-31', 'YYYY-MM-DD'), -12) THEN {amount} ELSE 0 END)) / 
NULLIF(SUM(CASE WHEN {trandate} BETWEEN ADD_MONTHS(TO_DATE(TO_CHAR(SYSDATE, 'YYYY') || '-01-01', 'YYYY-MM-DD'), -12) AND ADD_MONTHS(TO_DATE(TO_CHAR(SYSDATE, 'YYYY') || '-01-31', 'YYYY-MM-DD'), -12)THEN {amount} ELSE 0 END),0))

/*February */
((SUM(CASE WHEN {trandate} BETWEEN TO_DATE(TO_CHAR(SYSDATE, 'YYYY') || '-02-01', 'YYYY-MM-DD')AND TO_DATE(TO_CHAR(SYSDATE, 'YYYY') || '-02-28', 'YYYY-MM-DD') THEN {amount} ELSE 0 END) - 
SUM( CASE WHEN {trandate} BETWEEN ADD_MONTHS(TO_DATE(TO_CHAR(SYSDATE, 'YYYY') || '-02-01', 'YYYY-MM-DD'), -12) AND ADD_MONTHS(TO_DATE(TO_CHAR(SYSDATE, 'YYYY') || '-02-28', 'YYYY-MM-DD'), -12) THEN {amount} ELSE 0 END)) / 
NULLIF(SUM(CASE WHEN {trandate} BETWEEN ADD_MONTHS(TO_DATE(TO_CHAR(SYSDATE, 'YYYY') || '-02-01', 'YYYY-MM-DD'), -12) AND ADD_MONTHS(TO_DATE(TO_CHAR(SYSDATE, 'YYYY') || '-02-28', 'YYYY-MM-DD'), -12)THEN {amount} ELSE 0 END),0))

/*March */
((SUM(CASE WHEN {trandate} BETWEEN TO_DATE(TO_CHAR(SYSDATE, 'YYYY') || '-01-01', 'YYYY-MM-DD')AND TO_DATE(TO_CHAR(SYSDATE, 'YYYY') || '-01-31', 'YYYY-MM-DD') THEN {amount} ELSE 0 END) - 
SUM( CASE WHEN {trandate} BETWEEN ADD_MONTHS(TO_DATE(TO_CHAR(SYSDATE, 'YYYY') || '-01-01', 'YYYY-MM-DD'), -12) AND ADD_MONTHS(TO_DATE(TO_CHAR(SYSDATE, 'YYYY') || '-01-31', 'YYYY-MM-DD'), -12) THEN {amount} ELSE 0 END)) / 
NULLIF(SUM(CASE WHEN {trandate} BETWEEN ADD_MONTHS(TO_DATE(TO_CHAR(SYSDATE, 'YYYY') || '-01-01', 'YYYY-MM-DD'), -12) AND ADD_MONTHS(TO_DATE(TO_CHAR(SYSDATE, 'YYYY') || '-01-31', 'YYYY-MM-DD'), -12)THEN {amount} ELSE 0 END),0))

/*April */
((SUM(CASE WHEN {trandate} BETWEEN TO_DATE(TO_CHAR(SYSDATE, 'YYYY') || '-04-01', 'YYYY-MM-DD')AND TO_DATE(TO_CHAR(SYSDATE, 'YYYY') || '-04-30', 'YYYY-MM-DD') THEN {amount} ELSE 0 END) - 
SUM( CASE WHEN {trandate} BETWEEN ADD_MONTHS(TO_DATE(TO_CHAR(SYSDATE, 'YYYY') || '-04-01', 'YYYY-MM-DD'), -12) AND ADD_MONTHS(TO_DATE(TO_CHAR(SYSDATE, 'YYYY') || '-04-30', 'YYYY-MM-DD'), -12) THEN {amount} ELSE 0 END)) / 
NULLIF(SUM(CASE WHEN {trandate} BETWEEN ADD_MONTHS(TO_DATE(TO_CHAR(SYSDATE, 'YYYY') || '-04-01', 'YYYY-MM-DD'), -12) AND ADD_MONTHS(TO_DATE(TO_CHAR(SYSDATE, 'YYYY') || '-04-30', 'YYYY-MM-DD'), -12)THEN {amount} ELSE 0 END),0))

/*May */
((SUM(CASE WHEN {trandate} BETWEEN TO_DATE(TO_CHAR(SYSDATE, 'YYYY') || '-03-01', 'YYYY-MM-DD')AND TO_DATE(TO_CHAR(SYSDATE, 'YYYY') || '-03-31', 'YYYY-MM-DD') THEN {amount} ELSE 0 END) - 
SUM( CASE WHEN {trandate} BETWEEN ADD_MONTHS(TO_DATE(TO_CHAR(SYSDATE, 'YYYY') || '-03-01', 'YYYY-MM-DD'), -12) AND ADD_MONTHS(TO_DATE(TO_CHAR(SYSDATE, 'YYYY') || '-03-31', 'YYYY-MM-DD'), -12) THEN {amount} ELSE 0 END)) / 
NULLIF(SUM(CASE WHEN {trandate} BETWEEN ADD_MONTHS(TO_DATE(TO_CHAR(SYSDATE, 'YYYY') || '-03-01', 'YYYY-MM-DD'), -12) AND ADD_MONTHS(TO_DATE(TO_CHAR(SYSDATE, 'YYYY') || '-03-31', 'YYYY-MM-DD'), -12)THEN {amount} ELSE 0 END),0))

/*June */
((SUM(CASE WHEN {trandate} BETWEEN TO_DATE(TO_CHAR(SYSDATE, 'YYYY') || '-06-01', 'YYYY-MM-DD')AND TO_DATE(TO_CHAR(SYSDATE, 'YYYY') || '-06-30', 'YYYY-MM-DD') THEN {amount} ELSE 0 END) - 
SUM( CASE WHEN {trandate} BETWEEN ADD_MONTHS(TO_DATE(TO_CHAR(SYSDATE, 'YYYY') || '-06-01', 'YYYY-MM-DD'), -12) AND ADD_MONTHS(TO_DATE(TO_CHAR(SYSDATE, 'YYYY') || '-06-30', 'YYYY-MM-DD'), -12) THEN {amount} ELSE 0 END)) / 
NULLIF(SUM(CASE WHEN {trandate} BETWEEN ADD_MONTHS(TO_DATE(TO_CHAR(SYSDATE, 'YYYY') || '-06-01', 'YYYY-MM-DD'), -12) AND ADD_MONTHS(TO_DATE(TO_CHAR(SYSDATE, 'YYYY') || '-06-30', 'YYYY-MM-DD'), -12)THEN {amount} ELSE 0 END),0))

/*July */
((SUM(CASE WHEN {trandate} BETWEEN TO_DATE(TO_CHAR(SYSDATE, 'YYYY') || '-07-01', 'YYYY-MM-DD')AND TO_DATE(TO_CHAR(SYSDATE, 'YYYY') || '-07-31', 'YYYY-MM-DD') THEN {amount} ELSE 0 END) - 
SUM( CASE WHEN {trandate} BETWEEN ADD_MONTHS(TO_DATE(TO_CHAR(SYSDATE, 'YYYY') || '-07-01', 'YYYY-MM-DD'), -12) AND ADD_MONTHS(TO_DATE(TO_CHAR(SYSDATE, 'YYYY') || '-07-31', 'YYYY-MM-DD'), -12) THEN {amount} ELSE 0 END)) / 
NULLIF(SUM(CASE WHEN {trandate} BETWEEN ADD_MONTHS(TO_DATE(TO_CHAR(SYSDATE, 'YYYY') || '-07-01', 'YYYY-MM-DD'), -12) AND ADD_MONTHS(TO_DATE(TO_CHAR(SYSDATE, 'YYYY') || '-07-31', 'YYYY-MM-DD'), -12)THEN {amount} ELSE 0 END),0))

/*August*/
((SUM(CASE WHEN {trandate} BETWEEN TO_DATE(TO_CHAR(SYSDATE, 'YYYY') || '-08-01', 'YYYY-MM-DD')AND TO_DATE(TO_CHAR(SYSDATE, 'YYYY') || '-08-31', 'YYYY-MM-DD') THEN {amount} ELSE 0 END) - 
SUM( CASE WHEN {trandate} BETWEEN ADD_MONTHS(TO_DATE(TO_CHAR(SYSDATE, 'YYYY') || '-08-01', 'YYYY-MM-DD'), -12) AND ADD_MONTHS(TO_DATE(TO_CHAR(SYSDATE, 'YYYY') || '-08-31', 'YYYY-MM-DD'), -12) THEN {amount} ELSE 0 END)) / 
NULLIF(SUM(CASE WHEN {trandate} BETWEEN ADD_MONTHS(TO_DATE(TO_CHAR(SYSDATE, 'YYYY') || '-08-01', 'YYYY-MM-DD'), -12) AND ADD_MONTHS(TO_DATE(TO_CHAR(SYSDATE, 'YYYY') || '-08-31', 'YYYY-MM-DD'), -12)THEN {amount} ELSE 0 END),0))

/*September */
((SUM(CASE WHEN {trandate} BETWEEN TO_DATE(TO_CHAR(SYSDATE, 'YYYY') || '-09-01', 'YYYY-MM-DD')AND TO_DATE(TO_CHAR(SYSDATE, 'YYYY') || '-09-30', 'YYYY-MM-DD') THEN {amount} ELSE 0 END) - 
SUM( CASE WHEN {trandate} BETWEEN ADD_MONTHS(TO_DATE(TO_CHAR(SYSDATE, 'YYYY') || '-09-01', 'YYYY-MM-DD'), -12) AND ADD_MONTHS(TO_DATE(TO_CHAR(SYSDATE, 'YYYY') || '-09-30', 'YYYY-MM-DD'), -12) THEN {amount} ELSE 0 END)) / 
NULLIF(SUM(CASE WHEN {trandate} BETWEEN ADD_MONTHS(TO_DATE(TO_CHAR(SYSDATE, 'YYYY') || '-09-01', 'YYYY-MM-DD'), -12) AND ADD_MONTHS(TO_DATE(TO_CHAR(SYSDATE, 'YYYY') || '-09-30', 'YYYY-MM-DD'), -12)THEN {amount} ELSE 0 END),0))

/*October */
((SUM(CASE WHEN {trandate} BETWEEN TO_DATE(TO_CHAR(SYSDATE, 'YYYY') || '-10-01', 'YYYY-MM-DD')AND TO_DATE(TO_CHAR(SYSDATE, 'YYYY') || '-10-31', 'YYYY-MM-DD') THEN {amount} ELSE 0 END) - 
SUM( CASE WHEN {trandate} BETWEEN ADD_MONTHS(TO_DATE(TO_CHAR(SYSDATE, 'YYYY') || '-10-01', 'YYYY-MM-DD'), -12) AND ADD_MONTHS(TO_DATE(TO_CHAR(SYSDATE, 'YYYY') || '-10-31', 'YYYY-MM-DD'), -12) THEN {amount} ELSE 0 END)) / 
NULLIF(SUM(CASE WHEN {trandate} BETWEEN ADD_MONTHS(TO_DATE(TO_CHAR(SYSDATE, 'YYYY') || '-10-01', 'YYYY-MM-DD'), -12) AND ADD_MONTHS(TO_DATE(TO_CHAR(SYSDATE, 'YYYY') || '-10-31', 'YYYY-MM-DD'), -12)THEN {amount} ELSE 0 END),0))

/*November */
((SUM(CASE WHEN {trandate} BETWEEN TO_DATE(TO_CHAR(SYSDATE, 'YYYY') || '-11-01', 'YYYY-MM-DD')AND TO_DATE(TO_CHAR(SYSDATE, 'YYYY') || '-11-30', 'YYYY-MM-DD') THEN {amount} ELSE 0 END) - 
SUM( CASE WHEN {trandate} BETWEEN ADD_MONTHS(TO_DATE(TO_CHAR(SYSDATE, 'YYYY') || '-11-01', 'YYYY-MM-DD'), -12) AND ADD_MONTHS(TO_DATE(TO_CHAR(SYSDATE, 'YYYY') || '-11-30', 'YYYY-MM-DD'), -12) THEN {amount} ELSE 0 END)) / 
NULLIF(SUM(CASE WHEN {trandate} BETWEEN ADD_MONTHS(TO_DATE(TO_CHAR(SYSDATE, 'YYYY') || '-11-01', 'YYYY-MM-DD'), -12) AND ADD_MONTHS(TO_DATE(TO_CHAR(SYSDATE, 'YYYY') || '-11-30', 'YYYY-MM-DD'), -12)THEN {amount} ELSE 0 END),0))

/*December */
((SUM(CASE WHEN {trandate} BETWEEN TO_DATE(TO_CHAR(SYSDATE, 'YYYY') || '-12-01', 'YYYY-MM-DD')AND TO_DATE(TO_CHAR(SYSDATE, 'YYYY') || '-12-31', 'YYYY-MM-DD') THEN {amount} ELSE 0 END) - 
SUM( CASE WHEN {trandate} BETWEEN ADD_MONTHS(TO_DATE(TO_CHAR(SYSDATE, 'YYYY') || '-12-01', 'YYYY-MM-DD'), -12) AND ADD_MONTHS(TO_DATE(TO_CHAR(SYSDATE, 'YYYY') || '-12-31', 'YYYY-MM-DD'), -12) THEN {amount} ELSE 0 END)) / 
NULLIF(SUM(CASE WHEN {trandate} BETWEEN ADD_MONTHS(TO_DATE(TO_CHAR(SYSDATE, 'YYYY') || '-12-01', 'YYYY-MM-DD'), -12) AND ADD_MONTHS(TO_DATE(TO_CHAR(SYSDATE, 'YYYY') || '-12-31', 'YYYY-MM-DD'), -12)THEN {amount} ELSE 0 END),0))
